[package]
name = "cli_app"
version = "0.1.0"
edition = "2021"
description = "Command-line application examples"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"